config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :players, only: %i[ index show ]

  root 'pages#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  before_save :generate_slug

  def generate_slug
    return unless slug.blank?

    self.slug = "#{name} #{surname}".parameterize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
# frozen_string_literal: true

class HelloController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show; end

  # GET /players/new
  # def new
  #   @player = Player.new
  # end

  # GET /players/1/edit
  # def edit; end

  # POST /players or /players.json
  # def create
  #   @player = Player.new(player_params)

  #   respond_to do |format|
  #     if @player.save
  #       format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
  #       format.json { render :show, status: :created, location: @player }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @player.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /players/1 or /players/1.json
  # def update
  #   respond_to do |format|
  #     if @player.update(player_params)
  #       format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
  #       format.json { render :show, status: :ok, location: @player }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @player.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /players/1 or /players/1.json
  # def destroy
  #   @player.destroy!

  #   respond_to do |format|
  #     format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :surname, :height, :weight, :birthday, :birthmonth, :birthyear, :slug,
                                     :hs_year, :recruiter_id, :facebook, :instagram, :twitter, :hand,
                                     :positions_validated, :hs_position)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
# frozen_string_literal: true

module HelloCodespacesHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <img src="Octocat.png" class="App-logo" alt="logo" />
    <p>
      GitHub Codespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/hello/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="App">
  <header class="App-header">
    <p>
      GitHub Codespaces <span class="heart">♥️</span> Rails
    </p>
    <p class="small">
      Edit <code>app/views/pages/index.html.erb</code> and see changes live!
    </p>
  </header>
</div>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.number_field :birthday %>
  </div>

  <div>
    <%= form.label :birthmonth, style: "display: block" %>
    <%= form.number_field :birthmonth %>
  </div>

  <div>
    <%= form.label :birthyear, style: "display: block" %>
    <%= form.number_field :birthyear %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :hs_year, style: "display: block" %>
    <%= form.number_field :hs_year %>
  </div>

  <div>
    <%= form.label :recruiter_id, style: "display: block" %>
    <%= form.text_field :recruiter_id %>
  </div>

  <div>
    <%= form.label :facebook, style: "display: block" %>
    <%= form.text_field :facebook %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.label :hand, style: "display: block" %>
    <%= form.number_field :hand %>
  </div>

  <div>
    <%= form.label :positions_validated, style: "display: block" %>
    <%= form.number_field :positions_validated %>
  </div>

  <div>
    <%= form.label :hs_position, style: "display: block" %>
    <%= form.number_field :hs_position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= player.surname %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= player.height %>
  </p>

  <p>
    <strong>Slug:</strong>
    <%= player.slug %>
  </p>

  <p>
    <strong>Hs year:</strong>
    <%= player.hs_year %>
  </p>

</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Back to players", players_path %>
</div>